name: Give Strava Kudos 4

on:
  # Triggers every 4:00am UTC
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:


jobs:
  run-kudos-cron:
    runs-on: ubuntu-20.04
    environment: STRAVA_EMAIL
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: playwright install
      - run: python give_kudos_cp_club.py
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
      - run: python give_kudos_gtn_club.py
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}

        
